# Generated by Django 3.0.2 on 2020-05-05 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Automobiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('generation', models.CharField(max_length=30)),
                ('engine', models.CharField(max_length=30)),
                ('power', models.PositiveIntegerField()),
                ('torque', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stage1Configs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('new_power', models.PositiveIntegerField()),
                ('new_torque', models.PositiveIntegerField()),
                ('fk_automobile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='configs.Automobiles')),
                ('fk_userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stage2Configs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('new_power', models.PositiveIntegerField()),
                ('new_torque', models.PositiveIntegerField()),
                ('intake_system', models.CharField(max_length=50)),
                ('exhaust_system', models.CharField(max_length=50)),
                ('fk_automobile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='configs.Automobiles')),
                ('fk_stage1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='configs.Stage1Configs')),
                ('fk_userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stage3Configs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('new_power', models.PositiveIntegerField()),
                ('new_torque', models.PositiveIntegerField()),
                ('turbocharger', models.CharField(max_length=50)),
                ('fk_automobile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='configs.Automobiles')),
                ('fk_stage2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='configs.Stage2Configs')),
                ('fk_userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stage3PlusConfigs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('new_power', models.PositiveIntegerField()),
                ('new_torque', models.PositiveIntegerField()),
                ('details', models.TextField()),
                ('fk_automobile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='configs.Automobiles')),
                ('fk_stage3', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='configs.Stage3Configs')),
                ('fk_userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
