# Generated by Django 3.0.2 on 2020-05-16 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charact_mark', models.DecimalField(decimal_places=0, max_digits=1)),
                ('reliability_mark', models.DecimalField(decimal_places=0, max_digits=1)),
                ('fk_stage1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configs.Stage1Configs')),
                ('fk_stage2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configs.Stage2Configs')),
                ('fk_stage3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configs.Stage3Configs')),
                ('fk_stage3plus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configs.Stage3PlusConfigs')),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
